language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
script:
  - dotnet build --configuration Release
  - dotnet test Tests/YY.FIAS.Loader.Tests/YY.FIAS.Loader.Tests.csproj